blueprint:
  name: Auto-Off
  domain: automation
  input:
    target_switch:
      name: Target Switch
      selector:
        entity:
          domain: switch

variables:
  target_switch: !input target_switch
  switch_name: "{{ states[target_switch].name }}"

alias: "Auto-Off: {{ switch_name }}"
trigger:
  - platform: state
    entity_id: !input target_switch
    to: "on"

action:
  - delay: "00:00:30"
  - service: switch.turn_off
    target:
      entity_id: !input target_switch
